#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (C) 2019-2020 Geraldo Ribeiro <geraldo@intmain.io>
# ----------------------------------------------------------------------

git checkout master
git fetch upstream

git branch -D upstream-master-formatted || echo "Branch upstream-master not found"
git branch -D local-master-formatted    || echo "Branch local-master-formatted not found"

git checkout -b upstream-master-formatted upstream/master

CHECKS="readability-braces-around-statements,modernize-use-nullptr,modernize-use-override,modernize-raw-string-literal,modernize-deprecated-headers,modernize-loop-convert"
CXXFLAGS="-std=c++11 -I./include/"

for ext in cc hh h
do
  echo "Updating *.${ext}..."
  find . -name "*.${ext}" -exec sed -i "s/mutipart/multipart/g" {} \;
  find . -name "*.${ext}" -exec sed -i "s/Mutipart/Multipart/g" {} \;
  find . -name "*.${ext}" -exec clang-tidy {} -fix-errors -checks="${CHECKS}" -- ${CXXFLAGS} \;
  find . -name "*.${ext}" -exec clang-format -i {} \;
done

git commit -am "Code formatted"

git checkout -b local-master-formatted master
for ext in cc hh h
do
  echo "Updating *.${ext}..."
  find . -name "*.${ext}" -exec clang-tidy {} -fix-errors -checks=${CHECKS} -- ${CXXFLAGS} \;
  find . -name "*.${ext}" -exec clang-format -i {} \;
done

git commit -am "Code formatted" || echo "Nada a ser feito"

#git merge upstream-master-formatted --no-commit --no-ff

# git checkout master

# clang-tidy --list-checks -checks='*' | grep "modernize"
#    modernize-avoid-bind
#    modernize-deprecated-headers
#    modernize-loop-convert
#    modernize-make-shared
#    modernize-make-unique
#    modernize-pass-by-value
#    modernize-raw-string-literal
#    modernize-redundant-void-arg
#    modernize-replace-auto-ptr
#    modernize-shrink-to-fit
#    modernize-use-auto
#    modernize-use-bool-literals
#    modernize-use-default
#    modernize-use-emplace
#    modernize-use-nullptr
#    modernize-use-override
#    modernize-use-using
